# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: mycomputeragent

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'D:\Softwares\apache-maven-3.8.4-bin\apache-maven-3.8.4\bin\mvn.cmd clean install package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false